# # Generated by Django 5.0.7 on 2024-07-19 02:17

from django.db import migrations


class Migration(migrations.Migration):
    initial = True
    
    dependencies = [
    
    ]

    operations = [
    ]