# Generated by Django 5.0.7 on 2024-07-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
    ]
